wordpress:
  replicaCount: 3
  image:
    repository: wordpress
    tag: php8.2-apache
  storage:
    size: 10Gi
    storageClass: standard
    mountPath: /var/www/html




# to read db credentials from secret
wordpressCredentialSecret: []
  # name: wordpress-credentials


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "traefik"
  pathtype: ImplementationSpecific
  annotations: 
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "letsencrypt"

  hosts:
    - host: alireza.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


nodeSelector: {}

tolerations: []

affinity: {}


rsync:
  enabled: false
  sshkeysSecretName: ssh-keys

phpConfig:
  memory_limit: "1024M"
  max_execution_time: "600"
  post_max_size: "1024M"
  upload_max_filesize: "1024M"
  max_input_vars: "10000"
  max_input_time: "600"
  max_file_uploads: "30"


filemanager:
  enabled: false
  filemanagerPassword: '$2y$10$7IB4qWGIzRufTTuqKB21LOe.27wVAkoYVaohSlUt8gatIoKCQy6ba'
  filemanagerHost: 'filemanager.alireza.com'
  affinity:
    enabled: true
    type: required


sftp:
  enabled: false
  port: 30222
  affinity:
    enabled: true
    type: required


phpmyadmin:
  enabled: false
  phpmyadminHost: 'pma.alireza.com'
  mysqlHost: 'pxc-db-haproxy.pxc.svc.cluster.local:3306'


s3syncer:
  enabled: false
  service:
    type: ClusterIP
    port: 8080
  image:
    repository: alirezaramezanzadeh/nginx-s3syncer
    tag: latest
  mountPath: /var/www/html